### ISSUE TITLE
Сделать домашней

### ISSUE THREAD

**Issue by Bablzz** [Bablzz/QmlTraining#2]
реализовать возможность делать текущую(или любой введенный адрес) страницу домашней

**Comment by HAYMbl4** [comment]
Может сразу сделать страницу с настройками? где и будет указываться домашняя страница? а в строке URL'а, рядом с "Добавить закладку", приделать кнопочку "Сделать домашней". 

Хотя, возможности задавать домашнюю страницу в настройках думаю достаточно, но для отладки может быть полезна и кнопка.

**Comment by Bablzz** [comment]
Настройки будут, но не скоро. Сделаю кнопку, котороя будет менять label на название домашней страницы. А где вот хранить все страницы(избранное и т.д) я пока не знаю
